(()=>{'use strict';
const $=id=>document.getElementById(id),config=window.LEAD_TRACKER_CONFIG||{},statuses=['NEW','ASSIGNED','CONTACTED','QUALIFIED','PROPOSAL','NEGOTIATION','CONVERTED','LOST'];let token='',page=0,pageData=null,searchTimer=null,requestNumber=0;
function extractToken(){const match=location.hash.match(/^#\/organization\/([A-Za-z0-9_-]{20,})$/);return match?match[1]:''}
function esc(value=''){const el=document.createElement('span');el.textContent=String(value??'');return el.innerHTML}
function displayStatus(value=''){return String(value).toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function date(value){if(!value)return'—';const text=String(value),normalized=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/.test(text)&&!/(?:Z|[+-]\d{2}:?\d{2})$/i.test(text)?`${text}Z`:text,parsed=new Date(normalized);return Number.isNaN(parsed.getTime())?'—':parsed.toLocaleString()}
function setConnection(state,text){$('connectionDot').className=state;$('connectionText').textContent=text}
function showInvalid(message){$('appView').classList.add('hidden');$('invalidView').classList.remove('hidden');$('invalidMessage').textContent=message||'This link is invalid, expired, or has been disabled. Ask the CRM administrator for an active link.';setConnection('offline','Access unavailable')}
async function api(path){const response=await fetch(`${String(config.apiBaseUrl||'').replace(/\/$/,'')}${path}`,{headers:{'X-Lead-Tracking-Token':token},cache:'no-store',referrerPolicy:'no-referrer'});if(!response.ok){let body={};try{body=await response.json()}catch(_){}const error=new Error(body.message||body.detail||(response.status===401?'This tracker link is invalid, expired, or disabled.':`Unable to load lead status (${response.status}).`));error.status=response.status;throw error}return response.json()}
function renderSummary(data){const counts=data.statusCounts||{},closed=(counts.CONVERTED||0)+(counts.LOST||0);$('organizationName').textContent=data.organizationName||'Lead Status';$('totalCount').textContent=data.totalLeads||0;$('newCount').textContent=counts.NEW||0;$('activeCount').textContent=Math.max(0,(data.totalLeads||0)-(counts.NEW||0)-closed);$('convertedCount').textContent=counts.CONVERTED||0}
function renderList(data){pageData=data;const items=data.items||[];$('loading').classList.add('hidden');$('leadTable').classList.toggle('hidden',!items.length);$('emptyState').classList.toggle('hidden',Boolean(items.length));$('leadRows').innerHTML=items.map(lead=>{const reference=lead.publicReference||lead.reference||'',source=lead.sourceName||lead.source||'—';return`<tr><td class="lead-name">${esc(lead.leadName)}</td><td class="reference" title="Stable public lead ID">${esc(reference||'—')}</td><td>${esc(lead.assigneeName||'Unassigned')}</td><td><span class="pill ${esc(String(lead.status).toLowerCase())}">${esc(displayStatus(lead.status))}</span></td><td>${esc(source)}</td><td>${esc(date(lead.updatedAt))}</td><td>${reference?`<button class="open-button" data-reference="${esc(reference)}">View status →</button>`:'<span class="reference">Unavailable</span>'}</td></tr>`}).join('');$('pageInfo').textContent=data.totalElements?`Page ${data.page+1} of ${Math.max(1,data.totalPages)} · ${data.totalElements} leads`:'No leads';$('previousButton').disabled=data.page===0;$('nextButton').disabled=!data.hasNext}
async function load(target=0){const current=++requestNumber;page=Math.max(0,target);$('listError').classList.add('hidden');$('loading').classList.remove('hidden');$('leadTable').classList.add('hidden');$('emptyState').classList.add('hidden');const params=new URLSearchParams({page:String(page),size:'20',search:$('searchInput').value.trim(),assignee:$('assigneeFilter').value,status:$('statusFilter').value});try{const [summary,list]=await Promise.all([api('/api/public/lead-tracking/summary'),api(`/api/public/lead-tracking/leads?${params}`)]);if(current!==requestNumber)return;renderSummary(summary);renderList(list);setConnection('online','Live data')}catch(error){if(current!==requestNumber)return;if(error.status===401||error.status===403)return showInvalid(error.message);$('loading').classList.add('hidden');$('listError').textContent=error.message;$('listError').classList.remove('hidden');setConnection('offline','Temporarily unavailable')}}
async function openDetail(reference){if(!reference)return;try{const lead=await api(`/api/public/lead-tracking/leads/${encodeURIComponent(reference)}`);$('detailName').textContent=lead.leadName;$('detailReference').textContent=lead.publicReference||lead.reference||reference;$('detailAssignee').textContent=lead.assigneeName||'Unassigned';$('detailStatus').textContent=displayStatus(lead.status);$('detailStatus').className=`pill ${String(lead.status).toLowerCase()}`;$('detailSource').textContent=lead.sourceName||lead.source||'—';$('detailUpdated').textContent=date(lead.updatedAt);$('detailTimeline').innerHTML=(lead.timeline||[]).length?lead.timeline.map(item=>`<article><b>${esc(displayStatus(item.status))}</b><small>${esc(date(item.changedAt))}</small></article>`).join(''):'<p>No public status activity is available yet.</p>';$('detailBackdrop').classList.remove('hidden');document.body.style.overflow='hidden'}catch(error){if(error.status===401||error.status===403)return showInvalid(error.message);$('listError').textContent=error.message;$('listError').classList.remove('hidden')}}
function closeDetail(){$('detailBackdrop').classList.add('hidden');document.body.style.overflow=''}
async function loadAssignees(){try{const names=await api('/api/public/lead-tracking/assignees');$('assigneeFilter').insertAdjacentHTML('beforeend',names.map(name=>`<option value="${esc(name)}">${esc(name)}</option>`).join(''))}catch(error){if(error.status===401||error.status===403)showInvalid(error.message)}}
function init(){token=extractToken();if(!token)return showInvalid('The tracker token is missing from this link. Ask the CRM administrator to copy the complete organization tracker link.');$('invalidView').classList.add('hidden');$('appView').classList.remove('hidden');$('statusFilter').insertAdjacentHTML('beforeend',statuses.map(s=>`<option value="${s}">${displayStatus(s)}</option>`).join(''));$('refreshButton').onclick=()=>load(page);$('previousButton').onclick=()=>load(page-1);$('nextButton').onclick=()=>load(page+1);$('statusFilter').onchange=()=>load(0);$('assigneeFilter').onchange=()=>load(0);$('searchInput').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>load(0),350)};$('leadRows').onclick=e=>{const button=e.target.closest('[data-reference]');if(button)openDetail(button.dataset.reference)};$('detailClose').onclick=closeDetail;$('detailBackdrop').onclick=e=>{if(e.target===$('detailBackdrop'))closeDetail()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail()});loadAssignees();load(0)}
window.addEventListener('hashchange',()=>{if(extractToken()!==token)location.reload()});document.addEventListener('DOMContentLoaded',init);
})();
